FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
RUN echo "USING ROOT DOCKERFILE v2"

COPY backend/BeloteTournament.sln ./BeloteTournament.sln
COPY backend/src ./src

RUN dotnet restore
RUN dotnet publish ./src/BeloteTournament.Api/BeloteTournament.Api.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
ENV ASPNETCORE_URLS=http://0.0.0.0:${PORT}
COPY --from=build /app/publish ./
ENTRYPOINT ["dotnet", "BeloteTournament.Api.dll"]
